server:
  port: 8770

spring:
  application:
    name: authservice
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    notifexchange: notif.exchange
    logexchange: log.exchange
    logqueue: log.queue
    passwordresetconfirmationqueue: passwordresetconfirmation.queue
    enablenotifqueue: enablenotif.queue
    createnotificationmemberqueue: notificationmember.queue
    passwordresetqueue: passwordreset.queue
    logroutingkey: log.routingkey
    enablenotifroutingkey: enablenotif.routingkey
    passwordresetroutingkey: passwordreset.routingkey
    createnotificationmemberroutingkey: notificationmember.routingkey
    passwordresetconfirmationroutingkey: passwordresetroutingkey.routingkey

ribbon:
  eureka:
    enabled: false

