server:
  port: 8770

spring:
  application:
    name: authservice
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    notifexchange: notif.exchange
    logexchange: log.exchange
    logqueue: log.queue
    passwordresetconfirmationqueue: passwordresetconfirmation.queue
    enablenotifqueue: enablenotif.queue
    createnotificationmemberqueue: notificationmember.queue
    passwordresetqueue: passwordreset.queue
    logroutingkey: log.routingkey
    enablenotifroutingkey: enablenotif.routingkey
    passwordresetroutingkey: passwordreset.routingkey
    createnotificationmemberroutingkey: notificationmember.routingkey
    passwordresetconfirmationroutingkey: passwordresetroutingkey.routingkey


zuul:
  sensitive-headers:
  prefix: /api/v1
  ignored-services: '*'
  host:
    max-total-connections: 1000
    max-per-route-connections: 1000
    connect-timeout-millis: 1000000
    socket-timeout-millis: 1000000
  routes:
    notification-service:
        path: /notification/**
        serviceId: notificationservice
        stripPrefix: false

ribbon:
  eureka:
    enabled: false

